# https://www.arsouyes.org/en/blog/2020/30_duplicati
---
- name: Make sure the Duplicati container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/duplicati"
    pull: yes
    networks:
      - name: swag_internal_network
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}/Documents:/source/Documents:ro"
      - "{{ mergerfs_root }}/Pictures:/source/Pictures:ro"
    restart_policy: unless-stopped
