# https://www.arsouyes.org/en/blog/2020/30_duplicati
---
- name: Make sure the Duplicati container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/duplicati"
    pull: yes
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ docker_dir }}/config:/config"
      - "{{ mergerfs_root }}/docker-volumes-backup:/backups"
      - "{{ mergerfs_root }}/Documents:/source/Documents:ro"
      - "{{ mergerfs_root }}/Media:/source/Media:ro"
      - "{{ mergerfs_root }}/Music:/source/Music:ro"
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_internal_network
    connected:
      - "{{ container_name }}"
    appends: yes
  when: enable_swag
