---
- name: Create the necessary {{ container_name }} folder (1)
  file:
    path: "{{ docker_dir }}/{{ container_name }}/mariadb/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create the necessary {{ container_name }} folder (2)
  file:
    path: "{{ docker_dir }}/{{ container_name }}/storage/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the PhotoPrism MariaDB container is created and running
  docker_container:
    name: "photoprism-mariadb"
    image: "mariadb:latest"
    pull: yes
    command: "mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120"
    state: 'started'
    user: "{{ guid }}:{{ guid }}"
    env:
      "TZ": "{{ timezone }}"
      "MYSQL_ROOT_PASSWORD": "{{ mysql_root_password }}"
      "MYSQL_DATABASE": "photoprism_db"
      "MYSQL_USER": "{{ mysql_user }}"
      "MYSQL_PASSWORD": "{{ mysql_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/mariadb:/var/lib/mysql"
    restart_policy: unless-stopped

- name: Make sure the Photoprism container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: photoprism/photoprism:latest
    pull: yes
    expose:
      - "2342"
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    state: 'started'
    shm_size: 2G
    env:
      "PHOTOPRISM_GID": "{{ guid }}"
      "PHOTOPRISM_UID": "{{ guid }}"
      "PHOTOPRISM_UMASK": "0000"
      "TZ": "{{ timezone }}"
      "PHOTOPRISM_ADMIN_PASSWORD": "{{ photoprism_password }}"
      "PHOTOPRISM_SITE_URL": "http://{{ ansible_default_ipv4.address }}:2342/"
      "PHOTOPRISM_EXPERIMENTAL": "false"
      "PHOTOPRISM_HTTP_HOST": "0.0.0.0"
      "PHOTOPRISM_HTTP_PORT": "2342"
      "PHOTOPRISM_HTTP_COMPRESSION": "gzip"
      "PHOTOPRISM_DATABASE_DRIVER": "mysql"
      "PHOTOPRISM_DATABASE_SERVER": "photoprism-mariadb:3306"
      "PHOTOPRISM_DATABASE_NAME": "photoprism_db"
      "PHOTOPRISM_DATABASE_USER": "{{ mysql_user }}"
      "PHOTOPRISM_DATABASE_PASSWORD": "{{ mysql_password }}"
      "PHOTOPRISM_ORIGINALS_PATH": "/photoprism/originals"
      "PHOTOPRISM_STORAGE_PATH": "/photoprism/storage"
      "PHOTOPRISM_SIDECAR_PATH": "/photoprism/storage/sidecar"
      "PHOTOPRISM_CACHE_PATH": "/photoprism/storage/cache"
      "PHOTOPRISM_BACKUP_PATH": "/photoprism/storage/backup"
      "PHOTOPRISM_DISABLE_CHOWN": "false"
      "PHOTOPRISM_DISABLE_BACKUPS": "true"
      "PHOTOPRISM_DISABLE_WEBDAV": "true"
      "PHOTOPRISM_DETECT_NSFW": "true"
      "PHOTOPRISM_UPLOAD_NSFW": "false"
      "PHOTOPRISM_THUMB_FILTER": "lanczos"
      "PHOTOPRISM_THUMB_UNCACHED": "true"
      "PHOTOPRISM_THUMB_SIZE": "2048"
      "PHOTOPRISM_THUMB_SIZE_UNCACHED": "7680"
      "PHOTOPRISM_JPEG_SIZE": "7680"
      "PHOTOPRISM_JPEG_QUALITY": "92"
      "PHOTOPRISM_FFMPEG_ENCODER": "h264_qsv"
      "PHOTOPRISM_INIT": "intel-graphics tensorflow-amd64-avx"
      "TF_CPP_MIN_LOG_LEVEL": "0"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
    working_dir: "/photoprism"
    volumes:
      - "{{ mergerfs_root }}/Media/Photos:/photoprism/originals:ro"
      - "{{ docker_dir }}/{{ container_name }}/storage:/photoprism/storage"
    restart_policy: unless-stopped

- name: Schedule a library scan at 1 AM every day
  cron:
    name: Scan the PhotoPrism library
    hour: "1"
    job: "/usr/bin/docker exec photoprism /photoprism/bin/photoprism index"

- name: Schedule a database backup at 3 AM every day
  cron:
    name: Backup PhotoPrism database
    hour: "3"
    job: "/usr/bin/docker exec --user {{ username }}:{{ username }} photoprism /photoprism/bin/photoprism backup -i /photoprism/storage/backup/mysql/backup.sql"

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_internal_network
    connected:
      - "{{ container_name }}"
      - photoprism-mariadb
    appends: yes
  when: enable_swag