---
# 1. Add `stefangweichinger.ansible_rclone` to requirements.yml and install it (or run "ansible-galaxy install stefangweichinger.ansible_rclone")
# 2. Specify few variables in vars.yml, like `stable`/`beta` branch or version
# 3. Prepare config
# 4. Add crontab activities

- name: Install rclone
  ansible.builtin.include_role:
    name: stefangweichinger.ansible_rclone

- name: Update rclone remote password for `julia`
  become: no
  shell:
    cmd: "rclone --config  {{ rclone_config_location }} config password julia pass {{ rclone_password }}"

- name: Add jobs in crontab
  become: no
  cron:
    name: "Add synchronization tasks: catafalco <= julia ({{ item.src }})"
    minute: "{{ item.mm }}"
    hour: "{{ item.HH }}"
    job: "/usr/local/bin/rclone --config {{rclone_config_location }} sync julia:{{ item.src }} {{ mergerfs_root }}/{{ item.dst }} --exclude '@Recently-Snapshot/**' --exclude '@Recycle/**' --syslog --log-level NOTICE --syslog-facility SYSLOG && curl -fsS -m 10 --retry 5 -o /dev/null https://healthchecks.catafal.co/ping/{{ item.hc_uuid }}"
  with_items:
    - { src: "doc-alessio", dst: "Documents/alessio", HH: 8, mm: 0, hc_uuid: "23383efc-3976-4e21-a63a-1c722e3956e0" }
    - { src: "doc-sara", dst: "Documents/sara", HH: 8, mm: 10, hc_uuid: "bee92dc9-0a1d-4402-b555-ed8818d0c823"}
    - { src: "media-alessio", dst: "Pictures/alessio", HH: 8, mm: 20, hc_uuid: "436d641c-d5cf-4136-a4d4-bc2bbded1c47" }
    - { src: "media-sara", dst: "Pictures/sara", HH: 8, mm: 30, hc_uuid: "506bc5d6-01e5-49e3-a9da-be6e4df59771" }